# Generated by Django 5.0.4 on 2024-05-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="length",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
